# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 21:35
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiotrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_path', models.ImageField(
                    blank=True,
                    max_length=256,
                    null=True,
                    upload_to=app.models.cover.Cover.get_file_path,
                    verbose_name='Poster'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('original_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Cover')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_ms', models.PositiveIntegerField(default=2)),
                ('audiotracks', models.ManyToManyField(blank=True, to='app.Audiotrack')),
                ('countries', models.ManyToManyField(blank=True, to='app.Country')),
                ('cover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Cover')),
                ('directors', models.ManyToManyField(blank=True, to='app.Director')),
                ('dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DVD')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mediacontainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_path', models.ImageField(blank=True, max_length=256, null=True, upload_to=app.models.screenshot.Screenshot.get_file_path, verbose_name='Poster')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField(default=1)),
                ('cover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Cover')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('countries', models.ManyToManyField(to='app.Country')),
                ('cover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Cover')),
                ('directors', models.ManyToManyField(to='app.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Videoformat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=200)),
                ('ratio', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='serial',
            name='studios',
            field=models.ManyToManyField(to='app.Studio'),
        ),
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Serial'),
        ),
        migrations.AddField(
            model_name='film',
            name='mediacontainer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mediacontainer'),
        ),
        migrations.AddField(
            model_name='film',
            name='original_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Language'),
        ),
        migrations.AddField(
            model_name='film',
            name='screenshots',
            field=models.ManyToManyField(blank=True, to='app.Screenshot'),
        ),
        migrations.AddField(
            model_name='film',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
        ),
        migrations.AddField(
            model_name='film',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Serial'),
        ),
        migrations.AddField(
            model_name='film',
            name='studios',
            field=models.ManyToManyField(blank=True, to='app.Studio'),
        ),
        migrations.AddField(
            model_name='film',
            name='subtitles',
            field=models.ManyToManyField(blank=True, to='app.Subtitles'),
        ),
        migrations.AddField(
            model_name='film',
            name='videoformat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Videoformat'),
        ),
    ]
