# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='cover',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
        migrations.AlterField(
            model_name='season',
            name='cover',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='cover',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
    ]
