# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170819_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='RUS', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
