# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170819_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
