# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170819_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
