# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170819_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='original_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
        migrations.AlterField(
            model_name='videoformat',
            name='format',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='videoformat',
            name='resolution',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
