# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170819_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='jjj', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='alias',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
