# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170819_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='alias',
        ),
    ]
