# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_language_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
