# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170819_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
