# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170819_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitles',
            name='language',
        ),
        migrations.AddField(
            model_name='dvd',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='app.Language'),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitles',
            field=models.ManyToManyField(blank=True, related_name='subtitles', to='app.Language'),
        ),
        migrations.DeleteModel(
            name='Subtitles',
        ),
    ]
