# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170819_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='studios',
            field=models.ManyToManyField(blank=True, to='app.Studio'),
        ),
    ]
