# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_serial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
