# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170819_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
