# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170819_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
        migrations.AlterField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Serial'),
        ),
    ]
