# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170819_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='audiotracks',
            field=models.ManyToManyField(blank=True, null=True, to='app.Audiotrack'),
        ),
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, to='app.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='screenshots',
            field=models.ManyToManyField(blank=True, null=True, to='app.Screenshot'),
        ),
        migrations.AlterField(
            model_name='film',
            name='studios',
            field=models.ManyToManyField(blank=True, null=True, to='app.Studio'),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitles',
            field=models.ManyToManyField(blank=True, null=True, related_name='subtitles', to='app.Language'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='studios',
            field=models.ManyToManyField(blank=True, null=True, to='app.Studio'),
        ),
    ]
