# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170819_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Film'),
        ),
    ]
