# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170819_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='audiotracks',
        ),
        migrations.RemoveField(
            model_name='film',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='film',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='film',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='dvd',
        ),
        migrations.RemoveField(
            model_name='film',
            name='mediacontainer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='season',
        ),
        migrations.RemoveField(
            model_name='film',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='film',
            name='studios',
        ),
        migrations.RemoveField(
            model_name='film',
            name='subtitles',
        ),
        migrations.RemoveField(
            model_name='film',
            name='time_ms',
        ),
        migrations.RemoveField(
            model_name='film',
            name='videoformat',
        ),
    ]
