# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170819_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
