# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_film_time_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cover'),
        ),
        migrations.AddField(
            model_name='film',
            name='dvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DVD'),
        ),
        migrations.AddField(
            model_name='film',
            name='mediacontainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Mediacontainer'),
        ),
        migrations.AddField(
            model_name='film',
            name='original_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='app.Language'),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='film',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
        ),
        migrations.AddField(
            model_name='film',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Serial'),
        ),
        migrations.AddField(
            model_name='film',
            name='videoformat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Videoformat'),
        ),
    ]
