# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_film_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, to='app.Director'),
        ),
    ]
