# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_film_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='studios',
            field=models.ManyToManyField(blank=True, to='app.Studio'),
        ),
    ]
