# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_film_studios'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='subtitles',
            field=models.ManyToManyField(blank=True, related_name='subtitles', to='app.Language'),
        ),
    ]
