# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_film_audiotracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='film',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
